# Default values for wastebin.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: quxfoo/wastebin
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8088

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

wastebin:
  env:
    WASTEBIN_DATABASE_PATH: "/data/state.db"
    WASTEBIN_ADDRESS: "0.0.0.0:8088"
    WASTEBIN_TITLE: "Wastebin"
    WASTEBIN_THEME: "gruvbox"
    WASTEBIN_MAX_BODY_SIZE: "16777216" 