apiVersion: v2
name: plane
description: Project management tool from the future
type: application
version: 0.1.42
appVersion: v0.28.0
home: https://plane.so/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/plane/plane_icon_2.svg
sources:
  - https://github.com/makeplane/plane
maintainers:
  - name: Plane
    url: https://plane.so
keywords:
  - Project Management
  - Productivity
  - Collaboration
dependencies:
  - name: postgresql
    version: 16.7.26
    repository: oci://bitnamicharts.docker.pkg.emporium.rocks
  - name: redis
    repository: oci://bitnamicharts.docker.pkg.emporium.rocks
    version: 20.12.0
  - name: minio
    repository: oci://bitnamicharts.docker.pkg.emporium.rocks
    version: 15.0.2
annotations:
  displayName: Plane
  category: Productivity
  licenses: AGPL-3.0
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/plane/plane_gallery_1.png
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/plane/plane_gallery_2.png
