apiVersion: v2
name: penpot
description: The Open-Source design and prototyping platform
type: application
version: 1.0.67
appVersion: 2.7.1
dependencies:
  - condition: global.postgresqlEnabled
    name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
  - condition: global.redisEnabled
    name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
home: https://penpot.app
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/penpot/penpot_icon_2.svg
sources:
  - https://github.com/penpot/penpot
  - https://github.com/codechem/helm/tree/main/charts/penpot
maintainers:
  - name: codechem
    url: https://codechem.com
keywords:
  - Design
  - Prototype
annotations:
  displayName: Penpot
  category: Design
  licenses: MPL-2.0
  oidcRedirectPaths: /api/auth/oauth/oidc/callback
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/penpot/penpot_gallery_1.webp
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/penpot/penpot_gallery_2.webp
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/penpot/penpot_gallery_3.webp
