apiVersion: v2
name: lobechat
description: Lobe Chat - an open-source, modern-design AI chat framework.
type: application
version: 0.1.163
appVersion: "1.114.6"
home: https://lobehub.com/
icon: ""
sources:
  - https://github.com/lobehub/lobe-chat
keywords:
  - AI
annotations:
  displayName: LobeChat
  licenses: Apache License Version 2.0
  category: AI
  #gallery: ""
  oidcRedirectPaths: /api/auth
dependencies:
  - name: postgresql
    version: 16.x.x
    repository: oci://bitnamicharts.docker.pkg.emporium.rocks
  - name: minio
    version: 14.x.x
    repository: oci://bitnamicharts.docker.pkg.emporium.rocks
