apiVersion: v2
name: maybe
description: The OS for your personal finances
type: application
version: 0.1.2
appVersion: "0.6.0"
home: https://maybe.co/
icon: https://github.com/maybe-finance/maybe/blob/154a1a971b996713cfae3f62db9e7bc69da433f5/app/assets/images/logo-squircle.svg?raw=true
sources:
  - https://github.com/maybe-finance/maybe/
keywords:
  - Finance
annotations:
  displayName: maybe
  licenses: AGPL-3.0 license
  category: Finance
  gallery: "https://maybe.co/assets/screenshot-65d03882.png"
dependencies:
  - name: postgresql
    version: 16.x.x
    repository: https://charts.bitnami.com/bitnami
