name: Build VSCode Multi-Arch Images

on:
  push:
    branches: [main]
    paths:
      - 'charts/vscode/build/**'
      - '.github/workflows/build-vscode.yml'
    tags: ['v*']
  pull_request:
    branches: [main]
    paths:
      - 'charts/vscode/build/**'
      - '.github/workflows/build-vscode.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/vscode-codespace
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push using Makefile
        working-directory: ./charts/vscode/build
        env:
          PLATFORMS: linux/amd64,linux/arm64
          BUILD_ARGS: >-
            --push=${{ github.event_name != 'pull_request' }}
            --tags=${{ steps.meta.outputs.tags }}
            --labels=${{ steps.meta.outputs.labels }}
            --cache-from=type=gha
            --cache-to=type=gha,mode=max
        run: make ci-build
