name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - update/**
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.0.0
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cm-push plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git

      - name: Add helm repos
        run: |
          helm repo add bitnami oci://bitnamicharts.docker.pkg.emporium.rocks
          helm repo add gitea-charts https://dl.gitea.io/charts
          helm repo add requarks https://charts.js.wiki
          helm repo add gitlab https://charts.gitlab.io
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm repo add emporium-apps ${{ vars.HELM_REPO }} --username ${{ vars.HELM_USER }} --password ${{ secrets.HELM_PASSWORD }}
          helm repo add nextcloud https://nextcloud.github.io/helm/
          helm repo add minio https://charts.min.io/

      - name: Run cm-push
        run: |
          changed_charts=()

          for dir in charts/*; do
              if [ -d "$dir" ]; then
                  chart_dir="$dir/chart"
                  # if git diff --quiet HEAD~1 HEAD -- "$chart_dir"; then
                  #     continue
                  # fi
                  changed_charts+=("$chart_dir")
              fi
          done

          for chart in "${changed_charts[@]}"; do
              echo "Changed chart detected: $chart"
              #echo "Linting..."
              #helm lint $chart

              echo "Pushing..."
              # Package and push the chart
              helm cm-push $chart emporium-apps
          done
